### ISSUE TITLE
Make REDIS optional

### ISSUE THREAD

**Issue by litchfield** [Suor/django-cacheops#158]
I have a use-case here, where local_get is perfect for my needs, and I don't want cacheops trying to connect to redis for no reason.

**Comment by Suor** [comment]
It probably doesn't connect until something is cached anyway, since it uses
connection pooling. So you can just not do regular cache requests.

2015-08-04 13:34 GMT+07:00 Simon Litchfield <notifications@github.com>:

**Comment by litchfield** [comment]
It runs a sanity check on the settings- imo this should be removed

**Comment by Suor** [comment]
I looked a bit more into it and it looks like this is impossible to achieve. The thing is cacheops needs to send invalidate commands to redis whenever your `CACHEOPS` setting is not empty. This is because even if you always use `'local_get': True` and use only `get` op in `CACHEOPS` you can still use `some_queryset.cache()` anywhere, and it needs to be invalidated.

So cacheops is not good for your use case. I can probably find some simpler solution out there. If you insist on using cacheops you will need to monkey patch it to stop trying to invalidate stuff.
