### ISSUE TITLE
Stop using KEYS Redis command

### ISSUE THREAD

**Issue by BertrandBordage** [Suor/django-cacheops#172]
django-cacheops currently relies on the `KEYS` command from Redis to find what it needs to invalidate.
Unfortunately, as it is written [in the Redis docs](http://redis.io/commands/keys), it’s a debug feature that’s not supposed to be used like this, leading to multiple issues ([read this for more detail](http://django-cachalot.readthedocs.org/en/1.1.0/introduction.html#id3)).

**Comment by Suor** [comment]
cacheops doesn't use `KEYS` command during its normal operation since 2.0 and was never using it during `.save()` call. 

The link to cachalot docs you provided is an astonishing example of bad marketing I never met in open source before. For starters, it estimates both cache-machine and cacheops performance theoretically on some wrong understanding of how they work and should be used. Author states that `.save()` uses `./manage.py invalidate` command, which calls `invalidate_model()`, which uses `KEYS`, this is untrue, probably executing `invalidate.lua` script lead to this confusion. Also, cacheops invalidation is called "per table" there, which is also untrue, in that terms it could be called per query. [Here](http://hackflow.com/blog/2014/03/09/on-orm-cache-invalidation/) you can read an explanation of how cacheops works. There are more things like that there like cacheops not supporting `.prefetch_related()`, `.bulk_create()` or `.delete()`.

Overall cachalot is welcome addition to Django ecosystem as it replaces no longer maintained johnny-cache package. Simple per table cache is certainly useful for low update rate scenarios. It also has the advantage of being more worry free. However, for popular websites with high rate of updates (e.g. user submitted content) more granular invalidation approach is necessary. To achieve that cacheops and cache-machine make various trade-offs between self complexity, performance and correctness. And to effeciently use any of those user needs to understand that.

On eliminating `KEYS` anyway. To do that and still allow `invalidate_model()` to work cacheops will need to manage a set of keys depending on each model, alternatively it could manage timestamps or versions, like cachalot and johnny-cache do. Whatever the way used it will slow down (don't know how significant) and complicate normal operation. 

As this is performance consideration it should be only tackled on evidence of practical issues not on theoretical basis. There is no such evidence as I know of for 2.0+ cacheops, so fixing it now is premature optimization.

**Comment by BertrandBordage** [comment]
Yes, sorry, I made a mistake about that `KEYS` issue. I was basing my assumptions on the experience of django-cacheops I had 2 years ago and what I noticed about it. I updated that experience by reading the current source, but I mistook a Lua `invalidate` script call with a Django `invalidate` command call (as you btw guessed). That was enough to make bad assumptions about the performance, and I’m really sorry about that.

[I updated the django-cachalot docs](https://github.com/BertrandBordage/django-cachalot/blob/master/docs/introduction.rst#comparison-with-similar-tools), and this time made no assumption, I just tested every feature in the table instead of relying on what’s in the documentation and the issues. I removed features handled by every package. Tell me if you find something strange.

I totally agree with you that per table invalidation is not useful on websites with a high write rate. This is [the first thing](https://github.com/BertrandBordage/django-cachalot/blob/master/docs/introduction.rst#should-you-use-it) I wrote in the documentation. For the sake of clarity, I added it to the comparison table. By the way, I’m sorry it felt like a kind of “marketing” comparison, I just wanted to make something similar to django-packages, but with the specificity of ORM caches. I have nothing to sell, this comparison was just terribly missing IMO, as we don’t clearly understand what each solution proposes.  It was absolutely not clear to me before doing this, so I can’t imagine how lost a regular user would be, even after reading the whole documentation of each module.
