### ISSUE TITLE
No Caching being done

### ISSUE THREAD

**Issue by Laptopmini** [Suor/django-cacheops#176]
I was wondering if I could get some help setting up this library, I've been running into some problems.

A little background, Redis is setup properly and works fine, I've tested out its caching abilities using manual caching with a key (set/get).

The problem I am having is when I try to use cacheops with it to automate not only the caching, but more importantly their expiring. 

Here is how Cacheops is setup in the settings:
```python
CACHEOPS_REDIS = {
    'socket_timeout': 3,                  # connection timeout in seconds, optional
    'unix_socket_path': '/tmp/redis.sock' # replaces host and port
}

CACHEOPS = {
    'posts.*': {'ops': 'all', 'timeout': 60*60},
    'boards.*': {'ops': 'all', 'timeout': 60*60},
    'authentication.account': {'ops': 'all', 'timeout': 60*60},
}
```

So technically, this should automatically cache and expire any data related to my posts, boards and authentication.account models.

However, I have noticed no change in the response time on these models from the API. To compare, I have the average response time when I was manually caching the serialized data. With no caching, the API take an average response time of 3-5 seconds, when with caching they complete in 1-2 seconds.

Because what I've described above didn't seem to work, I tried to have my ViewSets directly cached from the url router. So for example, I used the following in an attempt to cache the API which retrieves all the Posts of a particular Board:
```python
boards_router = routers.NestedSimpleRouter(
    router, r'boards', lookup='board'
)
boards_router.register(r'posts', cached_view_as(Board, Post)(BoardsPostViewSet.as_view()), 'boards_posts')
```

However this creates the most bizarre behavior where the response returned by the class based viewset only contains a single empty post where all its values are None/Undefined.

Has anyone encountered this? Does it look like I am doing something wrong? Any help is appreciated as I am kind of at a loss here.

Thanks a lot!

**Comment by Suor** [comment]
Hi, sorry for slow response.

First, you can't say caching doesn't work if it makes things slower ;). Because under certain circumstances it can. E.g. cache is constantly invalidated or there is an everchanging element in cache key (usually current time or random number). Or caching is just too heavy.

To see what is happening you can use redis [MONITOR](http://redis.io/commands/MONITOR)  command or just debug your python code. I can't see anything obviously wrong with your code if you are using latest cacheops - 2.4.3. There however could be issues with older one:

1. `'ops': 'all'` only works since 2.2.1
2. `@cached_view_as()` only plays well with `TemplateView`s since 2.4.

These are first two that came to mind, there might be more. Older Django or Redis versions can also cause issues.

**Comment by Suor** [comment]
Please reopen with more info if still of interest.
