### ISSUE TITLE
Multiple database support bug

### ISSUE THREAD

**Issue by JessiePBhalerao** [Suor/django-cacheops#225]
I believe there is a bug in the support for multiple databases.  We had been using a database with the alias `replica` in our development django settings, and it has since been removed because it's not ready for use in Production.  In our development branch, with `replica` DB removed, and cacheops enabled, I am getting the error `The connection replica doesn't exist`  However, if I reinstate a `replica` database alias, as a mirror of the default DB, there is no error.  

The multiple db support docs say, 

> By default cacheops considers query result is same for same query, not depending on database queried.

However, it appears that cacheops is querying the _replica_ database alias rather than reading the current default DB.

**Comment by Suor** [comment]
The possible reason is that you get objects from cache with replica referenced in object state, then you make requests based on that object, which try to use replica connection. This has nothing to do with cacheops, but the way Django works and caching in general. 

The phrase you quote only means that cache key does not depend on connection used, so that objects returned from any database considered to be the same.

The possible approach for cacheops would be to introspect db state of returned objects and do something, not sure what. Not sure this should be somehow "fixed" on cacheops side. So I will close this for now, provide more info to reopen this - the exact case when you believe cacheops misbehaves.

Sorry for slow response.

**Comment by JessiePBhalerao** [comment]
You are right, this was solved by clearing cache.  It was difficult to diagnose due to multiple developers and therefore less knowledge of the prior state of the database routers, but ultimately not the fault of cacheops that that routing had changed, and the cache was too stale.  We've adjusted our timeouts, invalidation, and clear cache on deploys with all this in mind.
