### ISSUE TITLE
Cache connection failures on weird reasons

### ISSUE THREAD

**Issue by babus** [Suor/django-cacheops#278]
We are using django cacheops latest and opbeats to monitor the app performance. Recently we have been hit into the following cache measure(blue) in almost all the requests which we are not pretty sure why it is happening. It is certainly that the 50% of request time has been spent over there. We use a m4.xlarge cache instance just for cachops and have a user traffic of around 50K MAU.

![opbeat](https://user-images.githubusercontent.com/19949828/38410303-d74dfb60-39a1-11e8-931d-df5daf30e0de.PNG)

And we are creating name references for all the cache namespaces defined in settings at root level like the following in project.caches and import these names inside all the apps.

project/caches.py

```
from django.core.cache import caches

cache1 = caches['cache1']
cache2 = caches['cache2']
.
.
cacheN = caches[cacheN']
```

Setting.py

```
CACHES = {
    'cache1': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': DEFAULT_CACHE_PRIMARY,
        'TIMEOUT': 60 * 60,
        'OPTIONS': {
            'PARSER_CLASS': 'redis.connection.HiredisParser',
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 100,
                'timeout': 20,
            },
            'PICKLE_VERSION': -1,
        },
    },
.
.
}
```

wsgi.py

```
# Monkey patching standard libraries with gevent.
import gevent.monkey
gevent.monkey.patch_all()

# Monkey patching psycopg with psycogreen for async db I/O.
import psycogreen.gevent
psycogreen.gevent.patch_psycopg()

import redis.connection
import gevent.socket
redis.connection.socket = gevent.socket

import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings")

# Hook sentry to catch exceptions app level.
from raven.contrib.django.raven_compat.middleware.wsgi import Sentry
from django.core.wsgi import get_wsgi_application
application = Sentry(get_wsgi_application())
```

Server is configured with nginx + uwsgi(gevent patched) in a 4 core EC2 with 2 processes on each core and gevent concurrency of 1000 on each process. Also using django-redis for connection pooling. Our initial guess is that every request is trying to connect to every cache names as they are declared at project level but we assumed that it would be executed only once when the uwsgi loads and the connections will be kept persistent. Any suggestions would help us to a great extent. Thanks!

**Comment by Suor** [comment]
You are making many cache gets, which are on average 1.1 ms, this is normal unless redis is on the same server as app or right next to it. You can try pinging your redis server from your app server or use redis benchmarks without pipelining to determine whether this is the case. 

If this is still slower than expected than maybe you are using locking and some gets need to wait? Another possibility is that your redis is just overloaded, this could be because of heavy invalidation taking place, see Performance Tips, 5 in README.

**Comment by Suor** [comment]
BTW, django-cacheops doesn't use `CACHES` setting nor django-redis. It uses `CACHEOPS_REDIS` setting.

**Comment by babu-upcomer** [comment]
Thanks for the reply! We are running redis clusters using AWS elastic cache in the same AZ of the web and worker instances. 300 redis gets per request doesn't seem right to us. We'll check on to reduce the no of gets over there. Probably local caching the hot data using in-memory or file.

Other than that, I read through the performance tips, and are you suggesting to use `.nocache()` for complex queries that are using `__` joins and annotations? In that case we would endup adding that at many queries and also it won't be easy to remove if we want to disable cacheops in future as `nocache()` is not ORM function. Is their any thing like `cache()` so that we can be very specific about what to be cached and what to be fetched from db. I know there is a function decorator to cache all the queries inside the function but if there is anything like that to be applicable to queryset it would be easy to maintain.

**Comment by Suor** [comment]
Decorator doesn't cache request within function but caches entire function
calls, .inplace() can be used to save some CPU on app server by
constructing querysets faster, it doesn't reduce redis load.

.cache() could be used to plan caching particular ops like get, count or
fetch but that's it you need to come up with your own framework around
querysets to customize when to cache or just call .cache() or .nocache()
manually.

If you want to remove cacheops then you can disable it first, this way
.cache() and .nocache() will still be there but do nothing.

сб, 7 апр. 2018 г., 17:11 Babu <notifications@github.com>:

**Comment by Suor** [comment]
> Probably local caching the hot data using in-memory or file.
You can local cache with cacheops data that you don't need to invalidate much like geographic name, see `local_get`.

> complex queries that are using __ joins and annotations
If query will be repeated then you should cache it otherwise don't, its complexity not a big factor here. Complex queries tend to be invalidated more often though as they depend on many things, so consider using `.prefetch_related()` instead of `.select_related()`.  

You can also look at what queries do yo perform, maybe you can make less of them. Caching is to be used when you can't make it faster otherwise.

Some things still could be added to cacheops like a more granular maybe even callback based configuration on what to cache for example. Or integrating with `.prefetch_related()` better by using multiget and then excluding hit objects from query.
