### ISSUE TITLE
@cached_as function invalidated when unrelated object saved

### ISSUE THREAD

**Issue by mrmachine** [Suor/django-cacheops#347]
I want to invalidate a function when objects in a queryset are updated, via `@cached_as`. So I have something like this:

```python
>>> pks = range(10)

>>> LogEntry.objects.filter(pk__in=pks).count()
>>> 7

>>> @cached_as(LogEntry.objects.filter(pk__in=pks))
   .....: def f():
   .....:     print 'f'
   .....: 

>>> f()
f

>>> f()

```

All good so far. Now I go to save a `LogEntry` that is NOT related to the queryset I am using to cache:

```python
>>> LogEntry.objects.exclude(pk__in=pks)[0].save()

>>> f()
f

>>> f()

```

For some reason, the cache has been invalidated and the function executes again. It seems to be based on the number of PKs in the filter. This still works as expected:

```python
>>> pks = range(5)

>>> LogEntry.objects.filter(pk__in=pks).count()
>>> 4

>>> @cached_as(LogEntry.objects.filter(pk__in=pks))
   .....: def f():
   .....:     print 'f'
   .....: 

>>> f()
f

>>> f()

>>> LogEntry.objects.exclude(pk__in=pks)[0].save()

>>> f()

```

Nothing invalidated.

**Comment by Suor** [comment]
This is how it's implemented, cacheops creates a separate invalidation set for each of those pks, so to not horde redis with them when we have `__in` with more than `settings.CACHEOPS_LONG_DISJUNCTION` items the more crude invalidation is used.

Additionally "exclude in" has unknown set of object affecting it so it is invalidated same as `LogEntry.objects.all()`.

You can read more on how that works here http://hackflow.com/blog/2014/03/09/on-orm-cache-invalidation/

**Comment by mrmachine** [comment]
@Suor thanks for pointing me to that setting and blog post.

Unfortunately we're working with a slow and complex query with many subqueries to get the list of objects, and then we need to invalidate when many related objects with FKs back to that list of objects change.

We previously had many problems trying to pass the original query to `@cached_as`, and we had to do it many times for each related model.

So now we fetch the list of (hundreds of) PKs once, and use that in many (~10) `@cached_as` queryset samples via `__in` filter lookup. Basically this:

```python
pks = user.get_authorised_chapters_pks()  # complex with many subqueries and joins

@cached_as(
    Chapter.objects.filter(pk__in=pks),
    Mood.objects.filter(chapter__in=pks),
    Element.objects.filter(chapter__in=pks),
    PlaylistEntry.objects.filter(element__chapter__in=pks),
    ...  # etc.
)
def get_data():
    ...
data = get_data()
```

If my understanding is correct, we should be seeing a massive number of cache misses that consequently will re-execute the `get_data()` function, as unrelated objects from the same model (accessible only to other users) are being updated all the time.

Is the consequence of increasing this setting that:

1. performance of each cache hit degrades; or;
2. performance of invalidation in `post_save`, `post_delete` etc. signals degrades; or
3. we just need to allocate more memory to Redis to accomodate all the invalidation sets?

If 3, roughly how big is the additional invalidation set for each PK, assuming that the PK list is distinct for each user on our site, but has many (hundreds) of overlapping PKs? Will the storage cost be hundreds of additional invalidation sets, or hundreds of additional invalidation sets per user?

Alternatively, can you suggest an alternative (to increasing the value of that setting)? I had already looked into using something like `@cached_as(user)` with manual invalidation in the `post_save`, `post_delete` and `m2m_changed` signal handlers for all of those related models.

But some operations (M2M) were requiring that we invalidate thousands of users for common operations, which was also very slow.

**Comment by Suor** [comment]
If you increase then:
1. Performance of cache hit is not affected.
2. Cache write is slower for this query.
3. Invalidation is slower for all queries on these models (but less frequent for this particular query).
4. You might need to allocate more memory, this depends on how big your query results.

Also changing setting is global, so it will affect other queries the same way. Unless you change that dynamically:
```python
@override_settings(CACHEOPS_LONG_DISJUCTION=100500)
@cached_as(...)
def do_query(...):
    # ...
``` 

An invalidation set is created for each elementary conjunction say `chapter:id=123` or `chapter:id=123&category=2` or `chapter:` (no conditions), then each is filled with keys that depend on it. You may make your own calculations or simply test/bench it.

Instead of changing setting you may pass object lists:
```python
chapters = list(Chapter.objects.filter(...))
moods = list(Mood.objects.filter(...))

@cached_as(*chapters, *moods, ...)
def get_data(...):
    # ...
```
These are not affected by `CACHEOPS_LONG_DISJUCTION` setting.

The thing is, however, that selecting pks might lead you to stale cache. You say that you got those pks from `Chapter.objects.filter(category=2)` query and you want your `do_query()` cache to be invalidated when some chapter with category=2 changes, then if you simply pass those pks you it will work as expected for chapter update and deletion, but not for chapter addition. This is why cacheops uses conditions on different fields not only pks.

When you have some complex thing you are supposed to think of all the things that affect the result of it and express those as querysets:
```python
def some_complex_query(category=None, ...):
    chapter_qs = Chapter.objects.filter(category=category)
    element_qs = Element.objects.filter(...)
    playlist_entry_qs = PlaylistEntry.objects.filter(...)

    # Invalidating on all Mood changes as they change rare 
    # and affect lots of things - hard to express as qs
    @cached_as(chapter_qs, Mood, element_qs, playlist_entry_qs)
    def _get_data():
        # ... do the real query(ies) here
        return result  # everything combined

    return _get_data()
``` 
You are free to decide how granular or imperfect your invalidation would be, i.e. how close your invalidation querysets follow the actual ones.

**Comment by Suor** [comment]
**P.S.** If you can tolerate data to be stale for some time you might consider caching it by time and not use those complex invalidation conditions.

**Comment by mrmachine** [comment]
Thanks for this. I have rewritten our code to use `@cached` and pass in a UUID stored in Redis for each user in `extra`, and then manually update the UUID for all the invalidation events (e.g. `post_delete/save`, `m2m_changed`, for all the related models). This appears to have drastically reduced the number of cache misses, and is still fairly quick to invalidate.
