### ISSUE TITLE
BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE

### ISSUE THREAD

**Issue by benjamindell** [Suor/django-cacheops#444]
Hi. Every few weeks or so, my entire site goes down for a few minutes with numerous errors raised:

"BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE"

I'm finding it really difficult to trace the root cause. Is this something anyone else has encountered before?

**Comment by Suor** [comment]
Might be about [Performance tips](https://github.com/Suor/django-cacheops#performance-tips), 5 from README. The primary symptom is slow invalidation or cache memory being overrun. 

May also read [Memory usage cleanup](https://github.com/Suor/django-cacheops#memory-usage-cleanup), while this is not a fix. The fix if the above is the issue it to not cache complex queries.

You can also read on [how it works](http://suor.github.io/blog/2014/03/09/on-orm-cache-invalidation/).

**Comment by benjamindell** [comment]
Thanks. Super helpful.

Is there any way to detect / see which cache or part of my code is triggering the BUSY Redis error? I couldn’t seem to work out how to trace it back.

Ben

**Comment by Suor** [comment]
You can look at commands run against redis with [MONITOR](https://redis.io/commands/monitor/) or [SLOWLOG](https://redis.io/commands/slowlog-get/) commands. 

To understand what is happening you probably will need to read the how it works link from above, but invalidation script invocation will look something like:

```js
1676965334.196682 [13 127.0.0.1:59576] "EVALSHA" "0605214935a9ffcd4b9e5779300302540ff08da4" "1" "" "app_post" "{\"category_id\": 3, \"visible\": true, \"title\": \"...\", \"id\": 2}"
1676965334.196701 [13 lua] "smembers" "schemes:app_post"
1676965334.196711 [13 lua] "sunion" "conj:app_post:category_id=3" "conj:app_post:visible=true"
1676965334.196719 [13 lua] "unlink" "conj:app_post:category_id=3" "conj:app_post:visible=true"
1676965334.196727 [13 lua] "del" "q:424..." "q:b72..." "q:5f6..."
```

The first one is a script call itself the rest are commands run by that script. Then it goes over several steps:

1. It reads schemes first, which in this case were `(category_id,)` and `(visible,)` - these could be longer than 1 field, i.e. `(category_id, visible)`. 
2. For every scheme - list of fields - it makes a conjuction key, here there are two: `conj:app_post:category_id=3` and `conj:app_post:visible=true`. For two fields scheme it would hav been `conj:app_post:category_id=3&visible=true`. Values comes from object data passed to the invalidation script as JSON.
3. Each conj key contains a set of `q:...` keys, which are the ones holding data. So we drop all of them along with conj sets pointing to them.

The issue may be when those conjuction sets become very big, say many thousands or even millions of keys. Then `sunion` from above joins huge sets and produces a huge list. After which we also need to ran huge `del` command, which we actually split into chunks of 1000 because of Redis limitation.

The thing is by the time invalidation happens most of those keys may expire by time or by other condition already, and the majority of `q:...` keys are pointing to a non-existing keys. So one might avoid that slow invalidation by cleaning up obsolete keys from those conj sets. This is what `reapconjs` command does.

**Comment by Suor** [comment]
Preventing those conj sets from piling up is very app specific thing. For most people this just doesn't happen, when it happens you can try to find those sets by running `SCARD` for those keys or looking at `reapconjs` command logging output.

To get a big set you need two things to be aligned:
1. There are lots of different queries with the same eq conj condition.
2. It should be invalidated rarely to grow for some time.

E.g. if you run `Model.objects.filter(visible=True, expires__lt=datetime.now())` this query's cache will be added to `conj:model:visible=True` because no other equalities there but the rest of the query changes all the time. But then any new `Model` instance added, updated or deleted and being `visible=True` will drop that conj set, so the condition 2 fails here most probably.

However, if `Model` instances are added rarely, say once a day and you ran that query often you will bould up a huge conjection set, which will make for slow invalidation once it comes to it. Of cause caching query like that doesn't make any sense - it will always be new.

The more probable scenario is when you have complex filter conditions, which have a huge overall cardinality and neighter `__eq`, nor `__isnull=True`, nor small `__in` - less than 7 elements conditions.

**Comment by benjamindell** [comment]
Fantastic thanks. That's really helpful info.
