### ISSUE TITLE
Question on prefetch_related

### ISSUE THREAD

**Issue by lylepratt** [Suor/django-cacheops#88]
Hi! Thanks for creating this great solution.

I use prefetch_related for a few areas in my app, but I noticed that it is not supported. What will happen if I use prefetch_related with CacheOps? Will the separate fetch results just not cache? 

Also, Is select_related supported?

Many thanks for the clarification.

-Lyle

**Comment by Yurmusp** [comment]
When you say they do not "interfere" you mean, it is not cached, or properly invalidated?

**Comment by Yurmusp** [comment]
@Suor What happens if in select_related  master model is cached but related models are not?
Is this query cached? If yes, then does it track modification of related models data ? (i would guess no, but may be I'm wrong). Does it require manual invalidation of master model data on modification of related models data to work smoothly?

**Comment by Suor** [comment]
To all. m2m, select_related and prefetch_related are different things, here everything is mixed together. 

**1.** Only model which starts queryset affects whether it would be cached, timeout, etc. 

**2.** `.prefetch_related()` creates separate db queries, which are cached (if they are) and invalidated separately. These queries are no different from any other query in the form of `Model.objects.filter(pk__in=[...])`.

**3.** Changes to `.select_related()` objects do not cause invalidation. 

**4.** Changes to joined via condition objects, however, cause invalidation. So:

```python
Post.objects.filter(category__title='Python')
``` 
will be invalidated if Category with `title='Python'` is added, updated or deleted. This is since cacheops 2.0, so some ancient answers might say otherwise.

**5.** Changes to anything joined any other way not via conditions, e.g. via `.order_by()` do not cause invalidation.

**6.** m2m invalidation works quite well since cacheops 2.4 (for years). It had same issues as invalidation on joins before 2.0 and some bugs before 2.4.

**Comment by Suor** [comment]
@Yurmusp not sure what you mean by master and related models. A queryset with `.select_related()` makes single db query, so it either cached or not, can't be done partially. Also see answers 1 and 3 above.

**Comment by Yurmusp** [comment]
@Suor Thank you for the detailed answer.

**Comment by Yurmusp** [comment]
One more question, I think somewhat related.
Readme mentions caveat that 
>  8. Doesn't work right with multi-table inheritance.

What exactly does not work with Multi-inheritance models?
If I cache model  B that is inherited from A and 
I will do all queries out of managers of model B.
What will not work?

**Comment by Suor** [comment]
If you query and change the same model everything should work fine. The issue is then you query base and change sub or vice versa, see [this tests](https://github.com/Suor/django-cacheops/blob/4.0/tests/tests.py#L818-L837).

**Comment by Yurmusp** [comment]
I see. Thank you.
